exports.sv = {
  name: 'Namn',
  email: 'E-post',
  phone: 'Telefon',
  reduced: "Rabatt (studerande, pensionär) ",
  close: "Stäng",
  cancel: "Avbryt",
  save: "Spara",
  noplaces: "Inga platser reserverade!",
  over: "Beställningen överskrider återstående platser",
  troop: "Grupp (minst 10) ",
  mingroup: "Grupp måste ha mera än 9 platser",
  reserved: "Tack! Vi har nu registrerat din bokning",
  free: "Ledig",
  soldout: "Slutsåld",
  remains: " platser kvar",
  performances: "Föreställningar:",
  msg: "Meddelande: ",
  service: "Mat+teater-erbjudande",
  participate: "Deltar",
  help: "Ange hur många av er som deltar i vårt erbjudande om teater + mat",
  more: "Läs mera",
  places: "Platser"
};
